font Roboto fonts/Roboto.png fonts/Roboto.dat
texture tank textures/tank.png
texture scout textures/scout.png
texture worker textures/worker.png
texture water textures/water.png
texture trench textures/trench.png
texture glacier textures/glacier.png
texture dirt textures/mars.png
texture trench_hole textures/Trench_Hole.png
texture trench_wall textures/Trench_Wall.png
texture trench_canal textures/Trench_Canal.png
texture trench_corner textures/Trench_Corner.png
texture trench_tail textures/Trench_Tail.png
texture trench_tip textures/Trench_Tip.png
texture water_tank hud/Water_Tank.png
texture water_tank_back hud/Water_Tank_Back.png
texture background hud/stars.png
texture laser textures/laser.png
texture egg textures/egg.png
animation pump animations/pump.png
animation death animations/death.png
animation tile textures/tile_ground.png
animation dig animations/dig.png
animation fill animations/fill.png
